### ISSUE TITLE
Handle blank voIKeys list

### ISSUE THREAD

**Issue by jm-welch** [victorops/hubot-victorops#7]
Referring to [this](https://github.com/victorops/hubot-victorops/blob/master/src/victorops.coffee#L188-L209) section:

The `voIKeys` list is pulled from redis, but for a fresh install, there will be nothing there. Moving the `@robot.emit` and `@rcvVOEvent` [lines](https://github.com/victorops/hubot-victorops/blob/master/src/victorops.coffee#L206-L207) to the top of the try prints out both the alert data (from rcvVOEvent) and the "Not an alert", indicating that an error was captured during the try block.

If I rewrite the block to remove the try/catch, using the [existential operator](http://coffeescript.org/#operators) instead, the resulting block is as follows:

``` coffeescript
    else if data.MESSAGE == "TIMELINE_LIST_REPLY_MESSAGE"
      for item in data.PAYLOAD.TIMELINE_LIST
        if item.ALERT?
          @robot.emit "alert", item.ALERT
          @rcvVOEvent 'alert', item.ALERT

          # get a list of current victor ops incident keys in the brain
          voIKeys = @robot.brain.get "VO_INCIDENT_KEYS"

          # name the new key and set the brain
          voCurIName = item.ALERT["INCIDENT_NAME"]
          @robot.brain.set voCurIName, item.ALERT

          # update the list of current victor ops incident keys in the brain
          voIKeys.push
            name: voCurIName
            timestamp: new Date
          @robot.brain.set "VO_INCIDENT_KEYS", voIKeys

          # clean up victor ops incident keys in the brain
          @cleanupBrain()

        else
          @robot.logger.info "Not an alert."
```

Using this on a fresh install with no redis history exposes the error:

```
[Wed Mar 23 2016 00:05:03 GMT+0000 (UTC)] ERROR TypeError: Cannot call method 'push' of null
  at VictorOps.receiveWS (/opt/bot-master/node_modules/hubot-victorops/src/victorops.coffee:199:11, <js>:240:21)
  at WebSocket.<anonymous> (/opt/bot-master/node_modules/hubot-victorops/src/victorops.coffee:145:7, <js>:182:22)
  at WebSocket.emit (events.js:98:17)
  at Receiver.ontext (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/WebSocket.js:816:10)
  at /opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:477:18
  at Receiver.applyExtensions (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:364:5)
  at /opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:466:14
  at Receiver.flush (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:340:3)
  at Receiver.opcodes.1.finish (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:482:12)
  at Receiver.expectHandler (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:457:31)
  at Receiver.add (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:95:24)
  at CleartextStream.realHandler (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/WebSocket.js:800:20)
  at CleartextStream.emit (events.js:95:17)
  at CleartextStream.<anonymous> (_stream_readable.js:765:14)
  at CleartextStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at _stream_readable.js:420:7
  at process._tickCallback (node.js:448:13)
```

This seems to be blocking use of the adapter for new installations, as the brain is never getting updated and therefore nothing will be detected as an alert, which drives a number of scripts, including the victorops_handle_alert.coffee script we received from your team.

**Comment by danielhopkins** [comment]
Yep, that makes perfect sense. Thanks for the detailed note :)

You wouldn't happen to be have a PR ready to go for this? If not, NBD, I'll get it fixed in the near term.

**Comment by jm-welch** [comment]
Found it on my way out the door yesterday. Should be able to put together a PR for it today.

**Comment by jm-welch** [comment]
I think I've got a fix, but now that it's making it past the push, it's throwing an error on [`cleanupBrain()`](https://github.com/victorops/hubot-victorops/blob/master/src/victorops.coffee#L227-L238).

```
[Wed Mar 23 2016 16:03:48 GMT+0000 (UTC)] ERROR TypeError: Object Wed Mar 23 2016 16:03:48 GMT+0000 (UTC) has no method 'addDays'
  at /opt/bot-master/node_modules/hubot-victorops/src/victorops.coffee:236:14, <js>:278:38
  at Array.filter (native)
  at VictorOps.cleanupBrain (/opt/bot-master/node_modules/hubot-victorops/src/victorops.coffee:235:5, <js>:277:33)
  at VictorOps.receiveWS (/opt/bot-master/node_modules/hubot-victorops/src/victorops.coffee:206:11, <js>:246:18)
  at WebSocket.<anonymous> (/opt/bot-master/node_modules/hubot-victorops/src/victorops.coffee:145:7, <js>:182:22)
  at WebSocket.emit (events.js:98:17)
  at Receiver.ontext (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/WebSocket.js:816:10)
  at /opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:477:18
  at Receiver.applyExtensions (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:364:5)
  at /opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:466:14
  at Receiver.flush (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:340:3)
  at Receiver.opcodes.1.finish (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:482:12)
  at Receiver.expectHandler (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:457:31)
  at Receiver.add (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:95:24)
  at CleartextStream.realHandler (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/WebSocket.js:800:20)
  at CleartextStream.emit (events.js:95:17)    voIKeysFiltered = voIKeys.filter((item) ->
      if new Date(item.timestamp).addDays(1) < new Date
        @robot.brain.remove item.name
        return false
      true
  at CleartextStream.<anonymous> (_stream_readable.js:765:14)
  at CleartextStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at _stream_readable.js:420:7
  at process._tickCallback (node.js:448:13)
```

Looks like it's this block:

``` coffeescript
    voIKeysFiltered = voIKeys.filter((item) ->
      if new Date(item.timestamp).addDays(1) < new Date
        @robot.brain.remove item.name
        return false
      true
```

I'll have to dig into the Date object to find out what's wrong there. With the call to `cleanupBrain()` commented out, it seems to work fine.

**Comment by jm-welch** [comment]
Sorted out the `Date` object, but now a new error's showing up in `cleanupBrain()`. Looks like this is the way to add a day to a date:

``` coffeescript
    voIKeysFiltered = voIKeys.filter((item) ->
      if new Date(item.timestamp).getDate() + 1 < new Date
        @robot.brain.remove item.name
        return false
      true
    )
```

Now, it's making it past that part, but is complaining that `robot` is not defined in the next line.

```
[Wed Mar 23 2016 19:45:46 GMT+0000 (UTC)] ERROR ReferenceError: robot is not defined
  at /opt/bot-master/node_modules/hubot-victorops/src/victorops.coffee:237:9, <js>:279:11
  at Array.filter (native)
  at VictorOps.cleanupBrain (/opt/bot-master/node_modules/hubot-victorops/src/victorops.coffee:235:5, <js>:277:33)
  at VictorOps.receiveWS (/opt/bot-master/node_modules/hubot-victorops/src/victorops.coffee:206:11, <js>:246:18)
  at WebSocket.<anonymous> (/opt/bot-master/node_modules/hubot-victorops/src/victorops.coffee:145:7, <js>:182:22)
  at WebSocket.emit (events.js:98:17)
  at Receiver.ontext (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/WebSocket.js:816:10)
  at /opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:477:18
  at Receiver.applyExtensions (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:364:5)
  at /opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:466:14
  at Receiver.flush (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:340:3)
  at Receiver.opcodes.1.finish (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:482:12)
  at Receiver.expectHandler (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:457:31)
  at Receiver.add (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/Receiver.js:95:24)
  at CleartextStream.realHandler (/opt/bot-master/node_modules/hubot-victorops/node_modules/ws/lib/WebSocket.js:800:20)
  at CleartextStream.emit (events.js:95:17)
  at CleartextStream.<anonymous> (_stream_readable.js:765:14)
  at CleartextStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at _stream_readable.js:420:7
  at process._tickCallback (node.js:448:13)
```

**Comment by jm-welch** [comment]
``` coffeescript

  cleanupBrain: ->
    # get a list of all the victor ops incident keys in the brain
    voIKeys = @robot.brain.get "VO_INCIDENT_KEYS"

    # remove keys from the victor ops incident keys list and from the brain
    # if they are older than 24 hours
    voIKeysFiltered = voIKeys.filter((item) ->
      if new Date(item.timestamp).getDate() + 1 < new Date
        @robot.brain.remove item.name
        return false
      true
    )

    # set the victor ops incident keys list in the the brain to the updated
    # list value
    @robot.brain.set "VO_INCIDENT_KEYS", voIKeysFiltered
```

Is the `@robot.brain.remove item.name` within the conditional block required? I don't see where the items themselves are being pushed into the brain, only the list of recent keys, which it looks like we're overwriting in the last line anyway.

I'm fairly new to coffeescript/javascript, so I want to be sure that that line isn't required before I go blow it away. That said, this error looks to be all that's left to get this issue wrapped up.
